/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Automatically generate a sidebar from the docs folder structure.
  // This ensures every Markdown file under `docs/` is included and
  // the README at the project root is not treated as a doc.
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Scan everything under the /docs directory.
    },
  ],
};

module.exports = sidebars;

